name: Cypress Automation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    -name: Checkout
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome

      - name: Cypress run
        uses: cypress-io/github-action@v11.2.0
        with:
          build: npm run build
          start: npm start
