name: Cypress Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: cypress-io/github-action@v4
        with:
          browser: chrome
          #spec: cypress/integration/spec1.js

#       - name: Run Cypress UI Automation Tests
#         run: npx Cypress run --spec (fileName)

#       - name: Run Cypress API Automation Scripts
#         run: npx Cypress run --spec (fileName)
